name: Test Python App

on:
  push:
    paths:
      - 'app_python/'
      - '.github/'

jobs:
  test:
    name: Test/Lint app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.14
      - name: Install dependencies
        run: pip install -r app_python/requirements-dev.txt
      - name: Run linter
        run: flake8 app_python/app.py app_python/tests/
      - name: Run pytest
        run: pytest .
  push:
    name: Push docker image to Dockerhub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get current date for versioning
        uses: Kaven-Universe/github-action-current-date-time@v1
        id: current-time
        with:
          format: "YYYY.MM.DD"
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:app_python/"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME  }}/devops_app:latest, ${{ secrets.DOCKERHUB_USERNAME  }}/devops_app:${{ steps.current-time.outputs.time }}


    